### ISSUE TITLE
Url problemática.

### ISSUE THREAD

**Issue by tallysdev** [italo-mauricio/App-Brasileirao#14]
### bug na chamada de escudo o do time.

Quando fazemos a chamada da api e especialmente o escudo do time ele vem assim

Url da chamada:
 `"escudo": "https:\/\/cdn.api-futebol.com.br\/escudos\/638d3492a6e0b.svg"`  

Url que queremos: 
`"escudo": "https://cdn.api-futebol.com.br/escudos/638d3492a6e0b.svg"`

A principio nao sabemos como consertar isso, temos algumas opções:
1. Criar uma função para consertar o erro de string na chamada.
2. Cadastrar todos os escudos em um Enum.

**Comment by italo-mauricio** [comment]
String corrigirURL(String url) {
  return url.replaceAll('\\/', '/');
}

// Exemplo de uso
String urlComErro = "https:\/\/cdn.api-futebol.com.br\/escudos\/638d3492a6e0b.svg";
String urlCorrigida = corrigirURL(urlComErro);
print(urlCorrigida);

uma possível solução para o problema do / na API
