### ISSUE TITLE
Paleta de cores.

### ISSUE THREAD

**Issue by tallysdev** [italo-mauricio/App-Brasileirao#4]
## Escolher paleta de cores.

Deve ser escolhido e aprovado a paleta de cores do projeto.

site de paleta de cores sugerido ( https://realtimecolors.com/palettes/?colors=000000-ffffff-4685ff-f2f2f2-ffb084#generator ).

### Aprovações:
- [x] Gabriel
- [x] Italo
- [x] Tallys

**Comment by Japagabriel** [comment]
Gostei! dessa paleta, já pensou em quais cores a se utilizar como padrão ? ou deixa em aberto ainda para escolher ?

@Tallys-Aureliano 
@italo-mauricio

**Comment by tallysdev** [comment]
Vou escolher agora a noite e mostro a voces

**Comment by tallysdev** [comment]
A paleta seria Analogous:

## `#02ed29` , `#58fec6`, `#11fd74`, `#82fe76`, `#7bfd3a`  .
